name: Propagate Comic reader to S3
on: [push]
jobs:
  Update-S3-bucket-static:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
      - run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
        - shell: /bin/bash -e {0}
          env:
            HOST : ${{ secrets.HOST }}
            DEPLOYER_PEM_KEY : ${{ secrets.DEPLOYER_PEM_KEY }}
            PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
          # example-command "$SUPER_SECRET"
          run: |
            ssh -i "$DEPLOYER_PEM_KEY" "$HOST"